### ISSUE TITLE
SuspiciousFileOperation when saving sitemaps to STATIC_ROOT

### ISSUE THREAD

**Issue by globalmagic** [xaralis/django-static-sitemaps#19]
After upgrading to v2.0.0 I am getting the following django storage error when refreshing the sitemaps:

```
 File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/static_sitemaps/management/commands/refresh_sitemap.py", line 17, in handle_noargs
    generator.write_index()
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/static_sitemaps/generator.py", line 40, in write_index
    lastmod = self.write_page(site, page, filename, storage)
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/static_sitemaps/generator.py", line 96, in write_page
    if storage.exists(path):
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/django/core/files/storage.py", line 245, in exists
    return os.path.exists(self.path(name))
  File "/home/vagrant/.virtualenvs/env/local/lib/python2.7/site-packages/django/core/files/storage.py", line 261, in path
    raise SuspiciousFileOperation("Attempted access to '%s' denied." % name)
django.core.exceptions.SuspiciousFileOperation: Attempted access to '/vagrant/static/sitemap-static-1.xml' denied.
```

This occurs when STATICSITEMAPS_ROOT_DIR is set to STATIC_ROOT or any other directory. It only works when MEDIA_ROOT is used. It therefore appears to be a directory permissions issue, but the `collectstatic` command is able to write files to the static directory without errors.

This error occurs on windows and linux systems, including in a clean vagrant environment, which the above error message is taken from. 

Does anyone have any ideas on how to fix this?

**Comment by aiia** [comment]
**Hi, Xaralis,**

I'd like to reopen this issue as I bump the same error.
The reason looks to be in urls.pu
```
def serve_index(request):
    storage = _lazy_load(conf.STORAGE_CLASS)()
```
as FileSystemStorage initialized with location=MEDIA_ROOT by default (but I have STATIC_ROOT in my case, assigned to **conf.ROOT_DIR**).

So
```
def serve_index(request):
    storage = _lazy_load(conf.STORAGE_CLASS)(location=conf.ROOT_DIR)
```
looks to be correct.

Thanks,
Iho

**Comment by xaralis** [comment]
If you could provide a PR, it will be highly appreciated. Looks like to solution is quite simple and I would merge it immediately. Thanks.

**Comment by fpighi** [comment]
Thanks, I opened a pull request: #29

**Comment by sherzberg** [comment]
Any word on this getting merged? The PR #29 seems to work for me too.

**Comment by xaralis** [comment]
Merged it just now.

**Comment by ninad-goswamy** [comment]
_### 

> `[**SuspiciousFileOperation**]([url](

- 

- [ ] @ #1. url

))`

_
