### ISSUE TITLE
Sitemap for multiple languages

### ISSUE THREAD

**Issue by seocam** [xaralis/django-static-sitemaps#23]
I have a web page in multiple languages and I'd like my sitemaps linking to each one of the pages.

Since they have different URLs and different content for each URL all of them should be linked my the sitemap.

Perhaps that should be something to be implemented in Django instead of here...

**Comment by Allan-Nava** [comment]
@LuanP it works ?

**Comment by LuanP** [comment]
@Allan-Nava it worked by the time, but it has not being maintained ever since. I'm not sure how Django changed the sitemaps since that. Feel free to try it and open issues or PRs.

**Comment by Allan-Nava** [comment]
> @Allan-Nava it worked by the time, but it has not being maintained ever since. I'm not sure how Django changed the sitemaps since that. Feel free to try it and open issues or PRs.

I have to do like this:
```
class ItinerarySitemap(Sitemap):
    changefreq = "daily"
    priority = 0.6
    limit = 5000

    def items(self):
        i18n_itineraries = []
        for lang_code, lang in settings.LANGUAGES:
            activate(lang_code)
            for it in Itinerary.objects.select_related('origin', 'destination'):
                i18n_itineraries.append(it.get_absolute_url())
        return i18n_itineraries

    def location(self, obj):
        return obj
```
