### ISSUE TITLE
How to install on windows

### ISSUE THREAD

**Issue by danishravian** [xaralis/django-static-sitemaps#30]
Hello,

I am using windows machine to install this. But it is giving me this error: 

"Command "python setup.py egg_info" failed with error code 1 in C:\xx\AppData\Local\Temp\pip-build-jzlzgeur\django-static-sitemaps"

So, please tell me how can I solve this issue and install it. 

Thanks

**Comment by xaralis** [comment]
Sorry, I have no experience whatsoever with running Python apps on Windows. To be honest, I don't really think this little app would work flawlessly on Windows environment anyway. Maybe someone else could be more helpful on this topic.. :(
