### ISSUE TITLE
Upload Sitemap on S3 with django-storages

### ISSUE THREAD

**Issue by mpetyx** [xaralis/django-static-sitemaps#37]
Hello,

I am trying to override the default path of staticfils by adding the following line on my SETTINGS

`STATICSITEMAPS_ROOT_DIR = 'production-basket.s3.amazonaws.com/sitemaps/'`

As you can imagine, it doesn't work... Any ideas?
I just need to upload by sitemaps on S3 and serve them directly through there.

Thank you in advance,
Michael.

**Comment by dblado** [comment]
Setting STATICSITEMAPS_STORAGE works for me -- providing that all of your other settings for working w/ S3 are correct:

```
STATICSITEMAPS_STORAGE='storages.backends.s3boto.S3BotoStorage'
```

**Comment by mpetyx** [comment]
it didn't work originally for me, but i just did it manually through a script.. 
it works right now, but the solution i created is a "hack" that cannot be reused in a more general case.
thank you anyways for your response.

**Comment by oppianmatt** [comment]
Don't see that setting in the readme.

**Comment by xaralis** [comment]
@oppianmatt Good point, documented now.
