### ISSUE TITLE
Cannot generate sitemaps for multiple languages

### ISSUE THREAD

**Issue by oppianmatt** [xaralis/django-static-sitemaps#40]
I see there is a `STATICSITEMAPS_LANGUAGE` setting, but how to generate sitemaps for all languages?

**Comment by shtalinberg** [comment]
It's work for me
```
from django.conf import settings

from tips.sitemaps import TipSitemap, TipCategorySitemap


sitemaps = {}

for language in settings.LANGUAGES:
    sitemaps['tips-%s' % language[0]] = TipSitemap(language[0])
    sitemaps['tips-categories-%s' % language[0]] = TipCategorySitemap(language[0])
```

**Comment by paramono** [comment]
@xaralis 

This particular feature is already handled by django Sitemap classes, and you can use it with django-static-sitemaps out of the box, no extra code/PR necessary. See below.

@oppianmatt 

django-static-sitemaps uses django's sitemap dictionary, which maps to Sitemap classes you defined in your project. Add `i18n = True` attribute for each Sitemap that needs to generate multilingual urls. After doing so, django-static-sitemaps will include links for every language you have. Something like that:


```python
class WhateverDetailSitemap(sitemaps.Sitemap):
    priority = 0.8
    changefreq = 'daily'
    i18n = True

    def items(self):
        return Whatever.objects.all()

    def lastmod(self, obj):
        return obj.date_modified
```


Relevant documentation link: https://docs.djangoproject.com/en/dev/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.i18n

@shtalinberg 

This solution is probably ok if you want to split your languages across different files. The downside is that you have to maintain that extra piece of code that generates your sitemaps dict, making it a little less readable.

* * *

@oppianmatt 
Depending on your project, you may want to generate sitemaps using Google's guidelines:
https://support.google.com/webmasters/answer/2620865?hl=en

For each page you have in your sitemap, Google recommends to list its alternate language versions. This is not available in Django out of the box, but there a few solutions proposed for this issue:
https://code.djangoproject.com/ticket/27395#no1

Most likely, django-static-sitemaps will get this feature automatically as soon it lands in Django, but as of now, you'll have to use one of the solutions suggested in the ticket.

**Comment by xaralis** [comment]
@paramono Thanks for this. I'm not actively following django development anymore so I didn't realize this was already possible.
