### ISSUE TITLE
NoArgsCommand deprecated in Django 1.10

### ISSUE THREAD

**Issue by travismo123** [xaralis/django-static-sitemaps#44]
https://docs.djangoproject.com/es/1.10/internals/deprecation/

I think all that needs to be done is to switch NoArgsCommand to BaseCommand and define handle()

This is in refresh_sitemap.py

**Comment by xaralis** [comment]
@travismo123 I'll be happy to merge a PR if you're willing to help out.

**Comment by AlexeyUzhva** [comment]
Added pull request #45 that fixes this. Could you please merge?

**Comment by xaralis** [comment]
This is fixed by merging #45 in.
