### ISSUE TITLE
Celery Task Time Limit Setting

### ISSUE THREAD

**Issue by xmatos** [xaralis/django-static-sitemaps#54]
Hello!

Sometimes the **GenerateSitemap** task reaches celery's hard timeout. It would be nice to be able to adjust it in the settings. How about adding one for that?

Thanks!

**Comment by xaralis** [comment]
@xmatos Hello, I do not have time for this unfortunately. It should be fairly easy to implement though so I think you can do it and I will be happy to accept such pull request right away.

**Comment by xmatos** [comment]
ok! thanks!
