### ISSUE TITLE
Urls Structure incorrect for .xml.gz files?

### ISSUE THREAD

**Issue by digitaltommy** [xaralis/django-static-sitemaps#57]
I believe the current URL patterns don't pickup the compressed xml files, altering the include urls to the following solved the problem for me (just added the last line).

```python
from static_sitemaps.views import SitemapView

url(r'^sitemap\.xml$', SitemapView.as_view(), 
    kwargs={'section': 'sitemap'}, name='static_sitemaps_index'),
url(r'^(?P<section>sitemap-.+)\.xml$', SitemapView.as_view()),
url(r'^(?P<section>sitemap-.+)\.xml.gz$', SitemapView.as_view()),
```

Please let me know if I've missed something or made a mistake.

Thanks, Tom

**Comment by xaralis** [comment]
Yeah, that seems to do the job. Can you make it a pull request? Thx

**Comment by xaralis** [comment]
For the record: `django-static-sitemaps` are not here to serve your static files. Use [django.contrib.staticfiles](https://docs.djangoproject.com/en/2.0/ref/contrib/staticfiles/) for that. `static_sitemaps` only include root `sitemap.xml` for your convinience, but will not replicate behavior of Django `staticfiles` app.
