### ISSUE TITLE
str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by oppianmatt** [xaralis/django-static-sitemaps#59]
![image](https://user-images.githubusercontent.com/48596/34177274-f7b83416-e4fa-11e7-84e4-e00daaea9ae5.png)

looks like it's using python 3 syntax and the error is because we are using python 2

**Comment by oppianmatt** [comment]
this recent fix breaks py2.7 support https://github.com/xaralis/django-static-sitemaps/commit/4ff056df6361242c7e009658b376460e0b7daccc

at the moment pinning to version 4.4.0

**Comment by xaralis** [comment]
I decided not to prolong Python 2 support anymore. If you need it, you will have to stick with 4.4.0. Sorry about that but it's just too big effort.
