### ISSUE TITLE
is still alive the project?

### ISSUE THREAD

**Issue by Allan-Nava** [xaralis/django-static-sitemaps#63]
I could not create the sitemaps.xml

**Comment by xaralis** [comment]
@Allan-Nava This project is still being maintained. It is not in active development though as I'm not doing much Django anymore.

In order to help you, I would definitely need a lot more information comparing to what you have provided.

**Comment by xaralis** [comment]
No reaction, so closing. You might wanna try https://github.com/xaralis/django-static-sitemaps/releases/tag/4.6.0
