### ISSUE TITLE
celery 5 removed previsouly deprecated celery.task module 

### ISSUE THREAD

**Issue by dblado** [xaralis/django-static-sitemaps#74]
Using celery 5 with latest django-static-sitemaps doesn't work. In celery 4, the celery.tasks module was deprecated and then removed in version 5. You might be able to simply replace:

tasks.py:
```python
from celery.task import PeriodicTask
```
with
```python
from celery import Task
```
and
```python
    class GenerateSitemap(PeriodicTask):
```
with
```python
    class GenerateSitemap(Task):
```
I haven't tested this.

**Comment by salvacarrion** [comment]
I fixed it on a fork. You can install it using:
`pip install git+https://github.com/salvacarrion/django-static-sitemaps.git@master`
