### ISSUE TITLE
Ping deprecated

### ISSUE THREAD

**Issue by koutoftimer** [xaralis/django-static-sitemaps#78]
https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping

[`tasks.GenerateSitemap`][1] now throws 

```HTTP Error 404: Sitemaps ping is deprecated. See https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping.```

[1]: https://github.com/xaralis/django-static-sitemaps/blob/master/static_sitemaps/tasks.py#L13

**Comment by jeffbowen** [comment]
Until this gets removed you can set [`STATICSITEMAPS_PING_GOOGLE`](https://github.com/xaralis/django-static-sitemaps/blob/dd4dc66da78bd9f394eb8689eff3c406e3c45499/README.md?plain=1#L132) to `False` in your `settings.py`.

**Comment by Akay7** [comment]
I made a pr https://github.com/xaralis/django-static-sitemaps/pull/79

> Until this gets removed you can set [STATICSITEMAPS_PING_GOOGLE](https://github.com/xaralis/django-static-sitemaps/blob/dd4dc66da78bd9f394eb8689eff3c406e3c45499/README.md?plain=1#L132) to False in your settings.py.

It wont help at latest Django 5 because there's an import https://github.com/xaralis/django-static-sitemaps/blob/dd4dc66da78bd9f394eb8689eff3c406e3c45499/static_sitemaps/generator.py#L14 of `ping_google` that doesn't exist anymore at Django.

**Comment by koutoftimer** [comment]
@Akay7 I guess, it is "good first PR": just to wrap that import into if condition and, probably, add some tests.

**Comment by Akay7** [comment]
> I guess, it is good "first PR": just to wrap that import into if condition

There's no needs to ping google because that endpoint is deprecated on google side. And if there's no endpoint then there's no things to ping even with older version of Django.

>  and, probably, add some tests.

It's about removing functionality, in this case I should have removed the tests rather than writing them.

**Comment by mpasternak** [comment]
+1 for @Akay7 fix, is there a maintainer around?  @xaralis maybe?

**Comment by xaralis** [comment]
Released as v5.0.0, thanks @Akay7 . Sorry for the delay, tons of other stuff. https://pypi.org/project/django-static-sitemaps/5.0.0/
