### ISSUE TITLE
django-admin.py refresh_sitemap Unknown command: 'refresh_sitemap'

### ISSUE THREAD

**Issue by Nule** [xaralis/django-static-sitemaps#8]
Django 1.5: django-admin.py refresh_sitemap Unknown command: 'refresh_sitemap'

**Comment by dustydingo** [comment]
This problem continues to persist in Django 2.0+. It took me some time to figure out a solution to this very problem. In some operating systems the connection of path variables remains a problem (in my case Windows).

You can try the following steps to mitigate the same.

Include the following in your `settings.py`:
```python
INSTALLED_APPS = [
    ...
    'django.contrib.sites', # this was missing for me
    'django.contrib.sitemaps',
    ...
    'static_sitemaps',
]

SITE_ID = 1
```

Then you need to ensure that your database contains the required tables:
```python
python manage.py makemigrations
python manage.py migrate
```

Finally, you simply need to run the `refresh_sitemap` command using `manage.py`, not `django-admin`. Again, this looks like a system specific problem:
```python
python manage.py refresh_sitemap
```

This might be helpful to someone else. @xaralis would it be okay if I updated the documentation to reflect this for developers on Windows?

**Comment by xaralis** [comment]
@dustydingo Totally OK and appreciated.

**Comment by dustydingo** [comment]
Thanks @xaralis! I have submitted a merge request. If you would like any changes on that let me know.

**Comment by xaralis** [comment]
@dustydingo Merged.
